### PR TITLE
Create json of all update fields

### PR DESCRIPTION
**Pull request by bagsik**
Hey @jack-blackson ,

I have play a little bit with some variants.
What do you think about a json with all data?

### CODE REVIEW

**Comment by jack-blackson** [comment]
Can you show me how you plan to use this? Is this something you want to display in a vis?

**Comment by bagsik** [comment]
I have an external Vis where I use multiple dashboards.
Based of the content I also load data from iobroker over socket and subscribe to the lowest count of data points as possible. That is necessary, because of the low performance of some devices.

**Comment by jack-blackson** [comment]
This sounds interesting. So the reason why you would need it is that you want to move the data from iobroker to other devices that do something with this array? Because for a VIS, this object will without modification not work out.

**Comment by jack-blackson** [comment]
@bagsik It took some time, sorry, but it will be in the next release 2.3.0, which will be available in latest in the next days. Thanks!

**Pull request closed without merging**
